   server {
        listen 80;
        listen [::]:80; #若无 IPv6，此项可删除。
        return 301 https://$host$request_uri; #HTTP 自动跳转 HTTPS，让网站看起来更真实。
    }

    server {
        listen 443 ssl default_server; #仅版本不小于 v1.25.1 才配置，否则必须删除。
        listen [::]:443 ssl default_server; #仅版本不小于 v1.25.1 才配置，否则必须删除。另外若无 IPv6，此项也可删除。
        http2 on; #仅版本不小于 v1.25.1 才配置，否则必须删除。
        listen 443 ssl http2 default_server; #仅版本小于 v1.25.1 才配置，否则必须删除。
        listen [::]:443 ssl http2 default_server; #仅版本小于 v1.25.1 才配置，否必须则删除。另外若无 IPv6，此项也可删除。
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_reject_handshake on; #版本不小于 v1.19.4 才支持
    } #限定域名连接（包括禁止以 IP 方式访问网站）

    server {
        listen 443 quic reuseport; #仅版本不小于 v1.25.0 且 SSL 库支持 QUIC 才配置，否则必须删除。
        listen [::]:443 quic reuseport; #仅版本不小于 v1.25.0 且 SSL 库支持 QUIC 才配置，否则必须删除。另外若无 IPv6，此项也可删除。
        listen 443 ssl; #仅版本不小于 v1.25.1 才配置，否则必须删除。
        listen [::]:443 ssl; #仅版本不小于 v1.25.1 才配置，否则必须删除。另外若无 IPv6，此项也可删除。
        http2 on; #仅版本不小于 v1.25.1 才配置，否则必须删除。
        listen 443 ssl http2; #仅版本小于 v1.25.1 才配置，否则必须删除。
        listen [::]:443 ssl http2; #仅版本小于 v1.25.1 才配置，否则必须删除。另外若无 IPv6，此项也可删除。
        server_name h3a.example.com; #修改为自己的域名

        ssl_certificate /etc/xray/fullchain.pem; #修改为自己的证书，绝对路径。
        ssl_certificate_key /etc/xray/privkey.pem; #修改为自己的密钥，绝对路径。

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305; #若证书为 RSA 证书，所有 ECDSA 改为 RSA。
        ssl_prefer_server_ciphers on; #优先使用服务端的密码套件。（对如上 TLSv1.2 协议的密码套件有效）

        location /VLSpdG9k { #与 VLESS+XHTTP 应用中 path 对应
            grpc_pass grpc://127.0.0.1:2023; #转发给本机 VLESS+XHTTP 监听端口
            grpc_set_header Host $host;
            grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            add_header Alt-Svc 'h3=":443"; ma=86400'; #通告 HTTP/3 server 的可用性
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always; #启用 HSTS
            root /var/www/html; #修改为自己存放的 Web 文件路径
            index index.html index.htm;
        }
}
