stream {

    upstream web {
        server 127.0.0.1:8443;
        server [::1]:8443;
    }
    upstream xray {
        server 127.0.0.1:20000;
        server [::1]:20000;
    }

    map $ssl_preread_server_name $backend {
        xxxxx xray;
        default web;
    }

    server {
        listen 443 tcp;
        listen [::]:443 tcp;
        ssl_preread on;
        proxy_pass $backend;
    }
}



http......


server {
    listen 8443 quic reuseport;
    listen [::]:8443 quic reuseport;
    listen 8443 ssl;
    listen [::]:8443 ssl;    
    http2 on;
    server_name xxxxx;
    ssl_certificate /etc/letsencrypt/live/xxxxx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxxxx/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers on;
    resolver 8.8.8.8 1.1.1.1 valid=300s;
    resolver_timeout 5s;

    location / {
        root /var/www/html;
        index index.html index.htm;
        add_header Alt-Svc 'h3=":443"; ma=86400';
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    }

    location /download/ {
        alias           /download/;
        autoindex       on;
        autoindex_exact_size off;
        autoindex_localtime on;
    }
    sendfile on;
    tcp_nopush on;
}

server {
    listen 80;
    listen [::]:80;
    server_name xxxxx;
    if ($host = xxxxx) {
        return 301 https://$host$request_uri;
    }
}
