server {
        listen 8443 quic reuseport;
        listen [::]:8443 quic reuseport;
        listen 8443 ssl;
        listen [::]:8443 ssl;
        http2 on;
        server_name xxxxx;

        ssl_certificate /etc/letsencrypt/live/xxxxx/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xxxxx/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305;
        ssl_prefer_server_ciphers on;

        location / {
            add_header Alt-Svc 'h3=":443"; ma=86400';
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
            root /var/www/html;
            index index.html index.htm;
        }
}


stream {

    map $ssl_preread_server_name $backend {
        xxxxx vpn;
        www.pixiv.co.jp xray;
        default web;
    }
    upstream web {
        server 127.0.0.1:8443;
        server [::1]:8443;
    }
    upstream vpn {
        server 127.0.0.1:5555;
        server [::1]:5555;
    }
    upstream xray {
        server 127.0.0.1:10000;
        server [::1]:10000;
    }
    server {
        listen 443;
        listen [::]:443;
        proxy_pass $backend;
        ssl_preread on;
    }
}
